/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Public health endpoint; no authentication required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/firstrun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether registration is open (first-run state)
         * @description Returns first_run=true when the server has zero users yet.
         *     The SPA uses this to gate the /register page.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description First-run state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FirstRunResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * First-run registration
         * @description Creates the first admin user. Only succeeds when zero users
         *     exist (returns 409 otherwise).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registration successful; session cookie set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Registration disabled (not first run) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Logged in; session cookie set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session destroyed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged-in user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitHub PATs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListTokensResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a GitHub PAT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTokenRequest"];
                };
            };
            responses: {
                /** @description Token created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateTokenResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a GitHub PAT */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token in use by one or more connections */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connections */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant connections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListConnectionsResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Add a connection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConnectionRequest"];
                };
            };
            responses: {
                /** @description Connection created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateConnectionResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Duplicate connection */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a connection */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connection deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Connection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List repos in tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListReposResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/metrics": {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD inclusive start (default = to - 29d) */
                from?: string;
                /** @description YYYY-MM-DD inclusive end (default = today) */
                to?: string;
            };
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        /** Per-repo metrics time-series */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM-DD inclusive start (default = to - 29d) */
                    from?: string;
                    /** @description YYYY-MM-DD inclusive end (default = today) */
                    to?: string;
                };
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoMetricsResponse"];
                    };
                };
                /** @description Invalid date range */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Repo not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/metrics": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        /** Per-org summed metrics */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    org: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Org metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgMetricsResponse"];
                    };
                };
                /** @description Invalid date range */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Org not found (no repos in tenant) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engineers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List engineers (gh_users) in tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Engineers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEngineersResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engineers/{login}/metrics": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        /** Per-engineer metrics */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    login: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Engineer metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EngineerMetricsResponse"];
                    };
                };
                /** @description Invalid date range */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Engineer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-connection sync status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncStatusResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            version: string;
        };
        UserDTO: {
            /** Format: int64 */
            id: number;
            email: string;
            role: string;
        };
        MeResponse: {
            user: components["schemas"]["UserDTO"];
        };
        FirstRunResponse: {
            first_run: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        TokenDTO: {
            /** Format: int64 */
            id: number;
            label: string;
            scopes: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ListTokensResponse: {
            tokens: components["schemas"]["TokenDTO"][];
        };
        CreateTokenRequest: {
            label: string;
            pat: string;
            scopes?: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        CreateTokenResponse: {
            token: components["schemas"]["TokenDTO"];
        };
        ConnectionDTO: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            kind: "repo" | "org";
            owner: string;
            name?: string | null;
            /** Format: int64 */
            token_id: number;
            /** Format: date-time */
            backfill_from: string;
            status: string;
            /** Format: date-time */
            last_sync_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ListConnectionsResponse: {
            connections: components["schemas"]["ConnectionDTO"][];
        };
        CreateConnectionRequest: {
            /** @enum {string} */
            kind: "repo" | "org";
            owner: string;
            name?: string | null;
            /** Format: int64 */
            token_id: number;
            /** Format: date-time */
            backfill_from?: string | null;
        };
        CreateConnectionResponse: {
            connection: components["schemas"]["ConnectionDTO"];
        };
        RepoDTO: {
            /** Format: int64 */
            id: number;
            owner: string;
            name: string;
            default_branch: string;
            archived: boolean;
        };
        ListReposResponse: {
            repos: components["schemas"]["RepoDTO"][];
        };
        DailyRepoStatDTO: {
            date: string;
            /** Format: int64 */
            prs_opened: number;
            /** Format: int64 */
            prs_merged: number;
            /** Format: int64 */
            prs_closed: number;
            /** Format: int64 */
            deploys: number;
            /** Format: int64 */
            lead_time_seconds_p50?: number | null;
            /** Format: int64 */
            lead_time_seconds_p90?: number | null;
        };
        DailyReviewLatencyDTO: {
            date: string;
            /** Format: int64 */
            time_to_first_review_seconds_p50?: number | null;
            /** Format: int64 */
            time_to_first_review_seconds_p90?: number | null;
            /** Format: int64 */
            count: number;
        };
        DailyReviewLoadDTO: {
            date: string;
            /** Format: int64 */
            reviewer_gh_user_id: number;
            /** Format: int64 */
            reviews: number;
            /** Format: int64 */
            response_minutes_p50?: number | null;
        };
        RepoMetricsResponse: {
            repo: components["schemas"]["RepoDTO"];
            from: string;
            to: string;
            daily_stats: components["schemas"]["DailyRepoStatDTO"][];
            daily_review_latency: components["schemas"]["DailyReviewLatencyDTO"][];
            daily_review_load: components["schemas"]["DailyReviewLoadDTO"][];
        };
        OrgDailyStatsDTO: {
            date: string;
            /** Format: int64 */
            prs_opened: number;
            /** Format: int64 */
            prs_merged: number;
            /** Format: int64 */
            prs_closed: number;
            /** Format: int64 */
            deploys: number;
        };
        OrgDailyReviewLatencyDTO: {
            date: string;
            /** Format: int64 */
            count: number;
        };
        OrgDailyReviewLoadDTO: {
            date: string;
            /** Format: int64 */
            reviewer_gh_user_id: number;
            /** Format: int64 */
            reviews: number;
        };
        OrgMetricsResponse: {
            org: string;
            from: string;
            to: string;
            repos: components["schemas"]["RepoDTO"][];
            daily_stats: components["schemas"]["OrgDailyStatsDTO"][];
            daily_review_latency: components["schemas"]["OrgDailyReviewLatencyDTO"][];
            daily_review_load: components["schemas"]["OrgDailyReviewLoadDTO"][];
        };
        EngineerDTO: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            gh_id: number;
            login: string;
            name?: string | null;
            avatar_url?: string | null;
        };
        ListEngineersResponse: {
            engineers: components["schemas"]["EngineerDTO"][];
        };
        DailyEngineerStatDTO: {
            date: string;
            /** Format: int64 */
            repo_id: number;
            /** Format: int64 */
            commits: number;
            /** Format: int64 */
            prs_opened: number;
            /** Format: int64 */
            prs_merged: number;
            /** Format: int64 */
            reviews_given: number;
            /** Format: int64 */
            comments: number;
            /** Format: int64 */
            additions: number;
            /** Format: int64 */
            deletions: number;
        };
        EngineerDailyReviewLoadDTO: {
            date: string;
            /** Format: int64 */
            repo_id: number;
            /** Format: int64 */
            reviews: number;
            /** Format: int64 */
            response_minutes_p50?: number | null;
        };
        EngineerMetricsResponse: {
            engineer: components["schemas"]["EngineerDTO"];
            from: string;
            to: string;
            daily_stats: components["schemas"]["DailyEngineerStatDTO"][];
            daily_review_load: components["schemas"]["EngineerDailyReviewLoadDTO"][];
        };
        SyncRunDTO: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: int64 */
            ok: number;
            /** Format: int64 */
            items: number;
            /** Format: int64 */
            rate_limit_remaining?: number | null;
            error: string;
        };
        ConnectionSyncDTO: {
            /** Format: int64 */
            connection_id: number;
            kind: string;
            owner: string;
            name?: string | null;
            status: string;
            /** Format: date-time */
            last_sync_at?: string | null;
            latest_run?: components["schemas"]["SyncRunDTO"] | null;
            last_success?: components["schemas"]["SyncRunDTO"] | null;
            last_failure?: components["schemas"]["SyncRunDTO"] | null;
        };
        SyncStatusResponse: {
            connections: components["schemas"]["ConnectionSyncDTO"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
