// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commits.sql

package sqlitedb

import (
	"context"
	"time"
)

const getCommit = `-- name: GetCommit :one
SELECT repo_id, sha, author_gh_user_id, committer_gh_user_id, authored_at, additions, deletions, message FROM commits WHERE repo_id = ?1 AND sha = ?2
`

type GetCommitParams struct {
	RepoID int64  `json:"repo_id"`
	Sha    string `json:"sha"`
}

func (q *Queries) GetCommit(ctx context.Context, arg GetCommitParams) (Commit, error) {
	row := q.db.QueryRowContext(ctx, getCommit, arg.RepoID, arg.Sha)
	var i Commit
	err := row.Scan(
		&i.RepoID,
		&i.Sha,
		&i.AuthorGhUserID,
		&i.CommitterGhUserID,
		&i.AuthoredAt,
		&i.Additions,
		&i.Deletions,
		&i.Message,
	)
	return i, err
}

const listCommitsByAuthorBetween = `-- name: ListCommitsByAuthorBetween :many
SELECT repo_id, sha, author_gh_user_id, committer_gh_user_id, authored_at, additions, deletions, message FROM commits
WHERE author_gh_user_id = ?1
  AND authored_at >= ?2
  AND authored_at < ?3
ORDER BY authored_at
`

type ListCommitsByAuthorBetweenParams struct {
	AuthorGhUserID int64     `json:"author_gh_user_id"`
	FromTs         time.Time `json:"from_ts"`
	ToTs           time.Time `json:"to_ts"`
}

func (q *Queries) ListCommitsByAuthorBetween(ctx context.Context, arg ListCommitsByAuthorBetweenParams) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, listCommitsByAuthorBetween, arg.AuthorGhUserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.RepoID,
			&i.Sha,
			&i.AuthorGhUserID,
			&i.CommitterGhUserID,
			&i.AuthoredAt,
			&i.Additions,
			&i.Deletions,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitsByRepoBetween = `-- name: ListCommitsByRepoBetween :many
SELECT repo_id, sha, author_gh_user_id, committer_gh_user_id, authored_at, additions, deletions, message FROM commits
WHERE repo_id = ?1
  AND authored_at >= ?2
  AND authored_at < ?3
ORDER BY authored_at
`

type ListCommitsByRepoBetweenParams struct {
	RepoID int64     `json:"repo_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

func (q *Queries) ListCommitsByRepoBetween(ctx context.Context, arg ListCommitsByRepoBetweenParams) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, listCommitsByRepoBetween, arg.RepoID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.RepoID,
			&i.Sha,
			&i.AuthorGhUserID,
			&i.CommitterGhUserID,
			&i.AuthoredAt,
			&i.Additions,
			&i.Deletions,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommit = `-- name: UpsertCommit :exec
INSERT INTO commits (
  repo_id, sha, author_gh_user_id, committer_gh_user_id,
  authored_at, additions, deletions, message
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
)
ON CONFLICT (repo_id, sha) DO UPDATE SET
  author_gh_user_id = excluded.author_gh_user_id,
  committer_gh_user_id = excluded.committer_gh_user_id,
  authored_at = excluded.authored_at,
  additions = excluded.additions,
  deletions = excluded.deletions,
  message = excluded.message
`

type UpsertCommitParams struct {
	RepoID            int64     `json:"repo_id"`
	Sha               string    `json:"sha"`
	AuthorGhUserID    int64     `json:"author_gh_user_id"`
	CommitterGhUserID int64     `json:"committer_gh_user_id"`
	AuthoredAt        time.Time `json:"authored_at"`
	Additions         int64     `json:"additions"`
	Deletions         int64     `json:"deletions"`
	Message           string    `json:"message"`
}

func (q *Queries) UpsertCommit(ctx context.Context, arg UpsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommit,
		arg.RepoID,
		arg.Sha,
		arg.AuthorGhUserID,
		arg.CommitterGhUserID,
		arg.AuthoredAt,
		arg.Additions,
		arg.Deletions,
		arg.Message,
	)
	return err
}
