// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package sqlitedb

import (
	"context"
	"time"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (tenant_id, kind, owner, name, token_id, backfill_from, status)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, tenant_id, kind, owner, name, token_id, backfill_from, status, last_sync_at, created_at
`

type CreateConnectionParams struct {
	TenantID     int64     `json:"tenant_id"`
	Kind         string    `json:"kind"`
	Owner        string    `json:"owner"`
	Name         *string   `json:"name"`
	TokenID      int64     `json:"token_id"`
	BackfillFrom time.Time `json:"backfill_from"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.TenantID,
		arg.Kind,
		arg.Owner,
		arg.Name,
		arg.TokenID,
		arg.BackfillFrom,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Owner,
		&i.Name,
		&i.TokenID,
		&i.BackfillFrom,
		&i.Status,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE id = ?1
`

func (q *Queries) DeleteConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, tenant_id, kind, owner, name, token_id, backfill_from, status, last_sync_at, created_at FROM connections WHERE id = ?1
`

func (q *Queries) GetConnection(ctx context.Context, id int64) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Owner,
		&i.Name,
		&i.TokenID,
		&i.BackfillFrom,
		&i.Status,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const listConnectionsByTenant = `-- name: ListConnectionsByTenant :many
SELECT id, tenant_id, kind, owner, name, token_id, backfill_from, status, last_sync_at, created_at FROM connections WHERE tenant_id = ?1 ORDER BY created_at
`

func (q *Queries) ListConnectionsByTenant(ctx context.Context, tenantID int64) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Owner,
			&i.Name,
			&i.TokenID,
			&i.BackfillFrom,
			&i.Status,
			&i.LastSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionLastSync = `-- name: UpdateConnectionLastSync :exec
UPDATE connections SET last_sync_at = ?1 WHERE id = ?2
`

type UpdateConnectionLastSyncParams struct {
	LastSyncAt *time.Time `json:"last_sync_at"`
	ID         int64      `json:"id"`
}

func (q *Queries) UpdateConnectionLastSync(ctx context.Context, arg UpdateConnectionLastSyncParams) error {
	_, err := q.db.ExecContext(ctx, updateConnectionLastSync, arg.LastSyncAt, arg.ID)
	return err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections SET status = ?1 WHERE id = ?2
`

type UpdateConnectionStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateConnectionStatus, arg.Status, arg.ID)
	return err
}
