// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_review_load.sql

package sqlitedb

import (
	"context"
)

const listDailyReviewLoadByRepoBetween = `-- name: ListDailyReviewLoadByRepoBetween :many
SELECT date, repo_id, reviewer_gh_user_id, reviews, response_minutes_p50 FROM daily_review_load
WHERE repo_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date, reviewer_gh_user_id
`

type ListDailyReviewLoadByRepoBetweenParams struct {
	RepoID   int64  `json:"repo_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) ListDailyReviewLoadByRepoBetween(ctx context.Context, arg ListDailyReviewLoadByRepoBetweenParams) ([]DailyReviewLoad, error) {
	rows, err := q.db.QueryContext(ctx, listDailyReviewLoadByRepoBetween, arg.RepoID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyReviewLoad
	for rows.Next() {
		var i DailyReviewLoad
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.ReviewerGhUserID,
			&i.Reviews,
			&i.ResponseMinutesP50,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyReviewLoadByReviewerBetween = `-- name: ListDailyReviewLoadByReviewerBetween :many
SELECT date, repo_id, reviewer_gh_user_id, reviews, response_minutes_p50 FROM daily_review_load
WHERE reviewer_gh_user_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date, repo_id
`

type ListDailyReviewLoadByReviewerBetweenParams struct {
	ReviewerGhUserID int64  `json:"reviewer_gh_user_id"`
	FromDate         string `json:"from_date"`
	ToDate           string `json:"to_date"`
}

func (q *Queries) ListDailyReviewLoadByReviewerBetween(ctx context.Context, arg ListDailyReviewLoadByReviewerBetweenParams) ([]DailyReviewLoad, error) {
	rows, err := q.db.QueryContext(ctx, listDailyReviewLoadByReviewerBetween, arg.ReviewerGhUserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyReviewLoad
	for rows.Next() {
		var i DailyReviewLoad
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.ReviewerGhUserID,
			&i.Reviews,
			&i.ResponseMinutesP50,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyReviewLoad = `-- name: UpsertDailyReviewLoad :exec
INSERT INTO daily_review_load (
  date, repo_id, reviewer_gh_user_id, reviews, response_minutes_p50
) VALUES (
  ?1, ?2, ?3, ?4, ?5
)
ON CONFLICT (date, repo_id, reviewer_gh_user_id) DO UPDATE SET
  reviews = excluded.reviews,
  response_minutes_p50 = excluded.response_minutes_p50
`

type UpsertDailyReviewLoadParams struct {
	Date               string `json:"date"`
	RepoID             int64  `json:"repo_id"`
	ReviewerGhUserID   int64  `json:"reviewer_gh_user_id"`
	Reviews            int64  `json:"reviews"`
	ResponseMinutesP50 *int64 `json:"response_minutes_p50"`
}

func (q *Queries) UpsertDailyReviewLoad(ctx context.Context, arg UpsertDailyReviewLoadParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyReviewLoad,
		arg.Date,
		arg.RepoID,
		arg.ReviewerGhUserID,
		arg.Reviews,
		arg.ResponseMinutesP50,
	)
	return err
}
