// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_engineer_stats.sql

package sqlitedb

import (
	"context"
)

const deleteDailyEngineerStatsByDateRepo = `-- name: DeleteDailyEngineerStatsByDateRepo :exec
DELETE FROM daily_engineer_stats WHERE date = ?1 AND repo_id = ?2
`

type DeleteDailyEngineerStatsByDateRepoParams struct {
	Date   string `json:"date"`
	RepoID int64  `json:"repo_id"`
}

func (q *Queries) DeleteDailyEngineerStatsByDateRepo(ctx context.Context, arg DeleteDailyEngineerStatsByDateRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteDailyEngineerStatsByDateRepo, arg.Date, arg.RepoID)
	return err
}

const listDailyEngineerStatsByRepoBetween = `-- name: ListDailyEngineerStatsByRepoBetween :many
SELECT date, repo_id, gh_user_id, commits, prs_opened, prs_merged, reviews_given, comments, additions, deletions FROM daily_engineer_stats
WHERE repo_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date, gh_user_id
`

type ListDailyEngineerStatsByRepoBetweenParams struct {
	RepoID   int64  `json:"repo_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) ListDailyEngineerStatsByRepoBetween(ctx context.Context, arg ListDailyEngineerStatsByRepoBetweenParams) ([]DailyEngineerStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyEngineerStatsByRepoBetween, arg.RepoID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyEngineerStat
	for rows.Next() {
		var i DailyEngineerStat
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.GhUserID,
			&i.Commits,
			&i.PrsOpened,
			&i.PrsMerged,
			&i.ReviewsGiven,
			&i.Comments,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyEngineerStatsByUserBetween = `-- name: ListDailyEngineerStatsByUserBetween :many
SELECT date, repo_id, gh_user_id, commits, prs_opened, prs_merged, reviews_given, comments, additions, deletions FROM daily_engineer_stats
WHERE gh_user_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date, repo_id
`

type ListDailyEngineerStatsByUserBetweenParams struct {
	GhUserID int64  `json:"gh_user_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) ListDailyEngineerStatsByUserBetween(ctx context.Context, arg ListDailyEngineerStatsByUserBetweenParams) ([]DailyEngineerStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyEngineerStatsByUserBetween, arg.GhUserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyEngineerStat
	for rows.Next() {
		var i DailyEngineerStat
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.GhUserID,
			&i.Commits,
			&i.PrsOpened,
			&i.PrsMerged,
			&i.ReviewsGiven,
			&i.Comments,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyEngineerStats = `-- name: UpsertDailyEngineerStats :exec
INSERT INTO daily_engineer_stats (
  date, repo_id, gh_user_id,
  commits, prs_opened, prs_merged, reviews_given, comments,
  additions, deletions
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6, ?7, ?8,
  ?9, ?10
)
ON CONFLICT (date, repo_id, gh_user_id) DO UPDATE SET
  commits = excluded.commits,
  prs_opened = excluded.prs_opened,
  prs_merged = excluded.prs_merged,
  reviews_given = excluded.reviews_given,
  comments = excluded.comments,
  additions = excluded.additions,
  deletions = excluded.deletions
`

type UpsertDailyEngineerStatsParams struct {
	Date         string `json:"date"`
	RepoID       int64  `json:"repo_id"`
	GhUserID     int64  `json:"gh_user_id"`
	Commits      int64  `json:"commits"`
	PrsOpened    int64  `json:"prs_opened"`
	PrsMerged    int64  `json:"prs_merged"`
	ReviewsGiven int64  `json:"reviews_given"`
	Comments     int64  `json:"comments"`
	Additions    int64  `json:"additions"`
	Deletions    int64  `json:"deletions"`
}

func (q *Queries) UpsertDailyEngineerStats(ctx context.Context, arg UpsertDailyEngineerStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyEngineerStats,
		arg.Date,
		arg.RepoID,
		arg.GhUserID,
		arg.Commits,
		arg.PrsOpened,
		arg.PrsMerged,
		arg.ReviewsGiven,
		arg.Comments,
		arg.Additions,
		arg.Deletions,
	)
	return err
}
