// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_review_latency.sql

package sqlitedb

import (
	"context"
)

const listDailyReviewLatencyByRepoBetween = `-- name: ListDailyReviewLatencyByRepoBetween :many
SELECT date, repo_id, time_to_first_review_seconds_p50, time_to_first_review_seconds_p90, count FROM daily_review_latency
WHERE repo_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date
`

type ListDailyReviewLatencyByRepoBetweenParams struct {
	RepoID   int64  `json:"repo_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) ListDailyReviewLatencyByRepoBetween(ctx context.Context, arg ListDailyReviewLatencyByRepoBetweenParams) ([]DailyReviewLatency, error) {
	rows, err := q.db.QueryContext(ctx, listDailyReviewLatencyByRepoBetween, arg.RepoID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyReviewLatency
	for rows.Next() {
		var i DailyReviewLatency
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.TimeToFirstReviewSecondsP50,
			&i.TimeToFirstReviewSecondsP90,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyReviewLatencyByTenantOwnerBetween = `-- name: SumDailyReviewLatencyByTenantOwnerBetween :many
SELECT l.date AS date,
       CAST(SUM(l.count) AS INTEGER) AS count
FROM daily_review_latency l
JOIN repos r ON r.id = l.repo_id
WHERE r.tenant_id = ?1 AND r.owner = ?2
  AND l.date >= ?3 AND l.date < ?4
GROUP BY l.date
ORDER BY l.date
`

type SumDailyReviewLatencyByTenantOwnerBetweenParams struct {
	TenantID int64  `json:"tenant_id"`
	Owner    string `json:"owner"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

type SumDailyReviewLatencyByTenantOwnerBetweenRow struct {
	Date  string `json:"date"`
	Count int64  `json:"count"`
}

// SUM of the "count" column across every repo with (tenant_id, owner)
// for the date range. Percentile columns are intentionally not summed.
func (q *Queries) SumDailyReviewLatencyByTenantOwnerBetween(ctx context.Context, arg SumDailyReviewLatencyByTenantOwnerBetweenParams) ([]SumDailyReviewLatencyByTenantOwnerBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, sumDailyReviewLatencyByTenantOwnerBetween,
		arg.TenantID,
		arg.Owner,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumDailyReviewLatencyByTenantOwnerBetweenRow
	for rows.Next() {
		var i SumDailyReviewLatencyByTenantOwnerBetweenRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyReviewLatency = `-- name: UpsertDailyReviewLatency :exec
INSERT INTO daily_review_latency (
  date, repo_id,
  time_to_first_review_seconds_p50, time_to_first_review_seconds_p90, count
) VALUES (
  ?1, ?2,
  ?3, ?4, ?5
)
ON CONFLICT (date, repo_id) DO UPDATE SET
  time_to_first_review_seconds_p50 = excluded.time_to_first_review_seconds_p50,
  time_to_first_review_seconds_p90 = excluded.time_to_first_review_seconds_p90,
  count = excluded.count
`

type UpsertDailyReviewLatencyParams struct {
	Date                        string `json:"date"`
	RepoID                      int64  `json:"repo_id"`
	TimeToFirstReviewSecondsP50 *int64 `json:"time_to_first_review_seconds_p50"`
	TimeToFirstReviewSecondsP90 *int64 `json:"time_to_first_review_seconds_p90"`
	Count                       int64  `json:"count"`
}

func (q *Queries) UpsertDailyReviewLatency(ctx context.Context, arg UpsertDailyReviewLatencyParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyReviewLatency,
		arg.Date,
		arg.RepoID,
		arg.TimeToFirstReviewSecondsP50,
		arg.TimeToFirstReviewSecondsP90,
		arg.Count,
	)
	return err
}
