// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_repo_stats.sql

package sqlitedb

import (
	"context"
)

const deleteDailyRepoStatsByDateRepo = `-- name: DeleteDailyRepoStatsByDateRepo :exec
DELETE FROM daily_repo_stats WHERE date = ?1 AND repo_id = ?2
`

type DeleteDailyRepoStatsByDateRepoParams struct {
	Date   string `json:"date"`
	RepoID int64  `json:"repo_id"`
}

func (q *Queries) DeleteDailyRepoStatsByDateRepo(ctx context.Context, arg DeleteDailyRepoStatsByDateRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteDailyRepoStatsByDateRepo, arg.Date, arg.RepoID)
	return err
}

const listDailyRepoStatsByRepoBetween = `-- name: ListDailyRepoStatsByRepoBetween :many
SELECT date, repo_id, prs_opened, prs_merged, prs_closed, deploys, lead_time_seconds_p50, lead_time_seconds_p90 FROM daily_repo_stats
WHERE repo_id = ?1
  AND date >= ?2
  AND date < ?3
ORDER BY date
`

type ListDailyRepoStatsByRepoBetweenParams struct {
	RepoID   int64  `json:"repo_id"`
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
}

func (q *Queries) ListDailyRepoStatsByRepoBetween(ctx context.Context, arg ListDailyRepoStatsByRepoBetweenParams) ([]DailyRepoStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyRepoStatsByRepoBetween, arg.RepoID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyRepoStat
	for rows.Next() {
		var i DailyRepoStat
		if err := rows.Scan(
			&i.Date,
			&i.RepoID,
			&i.PrsOpened,
			&i.PrsMerged,
			&i.PrsClosed,
			&i.Deploys,
			&i.LeadTimeSecondsP50,
			&i.LeadTimeSecondsP90,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyRepoStats = `-- name: UpsertDailyRepoStats :exec
INSERT INTO daily_repo_stats (
  date, repo_id,
  prs_opened, prs_merged, prs_closed, deploys,
  lead_time_seconds_p50, lead_time_seconds_p90
) VALUES (
  ?1, ?2,
  ?3, ?4, ?5, ?6,
  ?7, ?8
)
ON CONFLICT (date, repo_id) DO UPDATE SET
  prs_opened = excluded.prs_opened,
  prs_merged = excluded.prs_merged,
  prs_closed = excluded.prs_closed,
  deploys = excluded.deploys,
  lead_time_seconds_p50 = excluded.lead_time_seconds_p50,
  lead_time_seconds_p90 = excluded.lead_time_seconds_p90
`

type UpsertDailyRepoStatsParams struct {
	Date               string `json:"date"`
	RepoID             int64  `json:"repo_id"`
	PrsOpened          int64  `json:"prs_opened"`
	PrsMerged          int64  `json:"prs_merged"`
	PrsClosed          int64  `json:"prs_closed"`
	Deploys            int64  `json:"deploys"`
	LeadTimeSecondsP50 *int64 `json:"lead_time_seconds_p50"`
	LeadTimeSecondsP90 *int64 `json:"lead_time_seconds_p90"`
}

func (q *Queries) UpsertDailyRepoStats(ctx context.Context, arg UpsertDailyRepoStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyRepoStats,
		arg.Date,
		arg.RepoID,
		arg.PrsOpened,
		arg.PrsMerged,
		arg.PrsClosed,
		arg.Deploys,
		arg.LeadTimeSecondsP50,
		arg.LeadTimeSecondsP90,
	)
	return err
}
