// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlitedb

import (
	"context"
	"time"
)

const listDeploymentsByRepoBetween = `-- name: ListDeploymentsByRepoBetween :many
SELECT gh_id, repo_id, environment, ref, sha, status, created_at FROM deployments
WHERE repo_id = ?1
  AND created_at >= ?2
  AND created_at < ?3
ORDER BY created_at
`

type ListDeploymentsByRepoBetweenParams struct {
	RepoID int64     `json:"repo_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

func (q *Queries) ListDeploymentsByRepoBetween(ctx context.Context, arg ListDeploymentsByRepoBetweenParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByRepoBetween, arg.RepoID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.GhID,
			&i.RepoID,
			&i.Environment,
			&i.Ref,
			&i.Sha,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployment = `-- name: UpsertDeployment :exec
INSERT INTO deployments (gh_id, repo_id, environment, ref, sha, status, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (gh_id) DO UPDATE SET
  repo_id = excluded.repo_id,
  environment = excluded.environment,
  ref = excluded.ref,
  sha = excluded.sha,
  status = excluded.status,
  created_at = excluded.created_at
`

type UpsertDeploymentParams struct {
	GhID        int64     `json:"gh_id"`
	RepoID      int64     `json:"repo_id"`
	Environment string    `json:"environment"`
	Ref         string    `json:"ref"`
	Sha         string    `json:"sha"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeployment,
		arg.GhID,
		arg.RepoID,
		arg.Environment,
		arg.Ref,
		arg.Sha,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
