// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gh_tokens.sql

package sqlitedb

import (
	"context"
	"time"
)

const createGhToken = `-- name: CreateGhToken :one
INSERT INTO gh_tokens (tenant_id, label, encrypted_pat, scopes, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, tenant_id, label, encrypted_pat, scopes, expires_at, created_at
`

type CreateGhTokenParams struct {
	TenantID     int64      `json:"tenant_id"`
	Label        string     `json:"label"`
	EncryptedPat []byte     `json:"encrypted_pat"`
	Scopes       string     `json:"scopes"`
	ExpiresAt    *time.Time `json:"expires_at"`
}

func (q *Queries) CreateGhToken(ctx context.Context, arg CreateGhTokenParams) (GhToken, error) {
	row := q.db.QueryRowContext(ctx, createGhToken,
		arg.TenantID,
		arg.Label,
		arg.EncryptedPat,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i GhToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.EncryptedPat,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGhToken = `-- name: DeleteGhToken :exec
DELETE FROM gh_tokens WHERE id = ?1
`

func (q *Queries) DeleteGhToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGhToken, id)
	return err
}

const getGhToken = `-- name: GetGhToken :one
SELECT id, tenant_id, label, encrypted_pat, scopes, expires_at, created_at FROM gh_tokens WHERE id = ?1
`

func (q *Queries) GetGhToken(ctx context.Context, id int64) (GhToken, error) {
	row := q.db.QueryRowContext(ctx, getGhToken, id)
	var i GhToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.EncryptedPat,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGhTokensByTenant = `-- name: ListGhTokensByTenant :many
SELECT id, tenant_id, label, encrypted_pat, scopes, expires_at, created_at FROM gh_tokens WHERE tenant_id = ?1 ORDER BY created_at
`

func (q *Queries) ListGhTokensByTenant(ctx context.Context, tenantID int64) ([]GhToken, error) {
	rows, err := q.db.QueryContext(ctx, listGhTokensByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GhToken
	for rows.Next() {
		var i GhToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.EncryptedPat,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
