// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gh_users.sql

package sqlitedb

import (
	"context"
	"time"
)

const getGhUser = `-- name: GetGhUser :one
SELECT id, tenant_id, gh_id, login, name, avatar_url, last_seen_at FROM gh_users WHERE id = ?1
`

func (q *Queries) GetGhUser(ctx context.Context, id int64) (GhUser, error) {
	row := q.db.QueryRowContext(ctx, getGhUser, id)
	var i GhUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GhID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.LastSeenAt,
	)
	return i, err
}

const getGhUserByGhID = `-- name: GetGhUserByGhID :one
SELECT id, tenant_id, gh_id, login, name, avatar_url, last_seen_at FROM gh_users WHERE tenant_id = ?1 AND gh_id = ?2
`

type GetGhUserByGhIDParams struct {
	TenantID int64 `json:"tenant_id"`
	GhID     int64 `json:"gh_id"`
}

func (q *Queries) GetGhUserByGhID(ctx context.Context, arg GetGhUserByGhIDParams) (GhUser, error) {
	row := q.db.QueryRowContext(ctx, getGhUserByGhID, arg.TenantID, arg.GhID)
	var i GhUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GhID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.LastSeenAt,
	)
	return i, err
}

const getGhUserByTenantLogin = `-- name: GetGhUserByTenantLogin :one
SELECT id, tenant_id, gh_id, login, name, avatar_url, last_seen_at FROM gh_users WHERE tenant_id = ?1 AND login = ?2 LIMIT 1
`

type GetGhUserByTenantLoginParams struct {
	TenantID int64  `json:"tenant_id"`
	Login    string `json:"login"`
}

func (q *Queries) GetGhUserByTenantLogin(ctx context.Context, arg GetGhUserByTenantLoginParams) (GhUser, error) {
	row := q.db.QueryRowContext(ctx, getGhUserByTenantLogin, arg.TenantID, arg.Login)
	var i GhUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GhID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.LastSeenAt,
	)
	return i, err
}

const listGhUsersByTenant = `-- name: ListGhUsersByTenant :many
SELECT id, tenant_id, gh_id, login, name, avatar_url, last_seen_at FROM gh_users WHERE tenant_id = ?1 ORDER BY login
`

func (q *Queries) ListGhUsersByTenant(ctx context.Context, tenantID int64) ([]GhUser, error) {
	rows, err := q.db.QueryContext(ctx, listGhUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GhUser
	for rows.Next() {
		var i GhUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GhID,
			&i.Login,
			&i.Name,
			&i.AvatarUrl,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGhUser = `-- name: UpsertGhUser :one
INSERT INTO gh_users (tenant_id, gh_id, login, name, avatar_url, last_seen_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (tenant_id, gh_id) DO UPDATE SET
  login = excluded.login,
  name = excluded.name,
  avatar_url = excluded.avatar_url,
  last_seen_at = excluded.last_seen_at
RETURNING id, tenant_id, gh_id, login, name, avatar_url, last_seen_at
`

type UpsertGhUserParams struct {
	TenantID   int64      `json:"tenant_id"`
	GhID       int64      `json:"gh_id"`
	Login      string     `json:"login"`
	Name       *string    `json:"name"`
	AvatarUrl  *string    `json:"avatar_url"`
	LastSeenAt *time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertGhUser(ctx context.Context, arg UpsertGhUserParams) (GhUser, error) {
	row := q.db.QueryRowContext(ctx, upsertGhUser,
		arg.TenantID,
		arg.GhID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.LastSeenAt,
	)
	var i GhUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GhID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.LastSeenAt,
	)
	return i, err
}
