// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"time"
)

type Commit struct {
	RepoID            int64     `json:"repo_id"`
	Sha               string    `json:"sha"`
	AuthorGhUserID    int64     `json:"author_gh_user_id"`
	CommitterGhUserID int64     `json:"committer_gh_user_id"`
	AuthoredAt        time.Time `json:"authored_at"`
	Additions         int64     `json:"additions"`
	Deletions         int64     `json:"deletions"`
	Message           string    `json:"message"`
}

type Connection struct {
	ID           int64      `json:"id"`
	TenantID     int64      `json:"tenant_id"`
	Kind         string     `json:"kind"`
	Owner        string     `json:"owner"`
	Name         *string    `json:"name"`
	TokenID      int64      `json:"token_id"`
	BackfillFrom time.Time  `json:"backfill_from"`
	Status       string     `json:"status"`
	LastSyncAt   *time.Time `json:"last_sync_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type DailyEngineerStat struct {
	Date         string `json:"date"`
	RepoID       int64  `json:"repo_id"`
	GhUserID     int64  `json:"gh_user_id"`
	Commits      int64  `json:"commits"`
	PrsOpened    int64  `json:"prs_opened"`
	PrsMerged    int64  `json:"prs_merged"`
	ReviewsGiven int64  `json:"reviews_given"`
	Comments     int64  `json:"comments"`
	Additions    int64  `json:"additions"`
	Deletions    int64  `json:"deletions"`
}

type DailyRepoStat struct {
	Date               string `json:"date"`
	RepoID             int64  `json:"repo_id"`
	PrsOpened          int64  `json:"prs_opened"`
	PrsMerged          int64  `json:"prs_merged"`
	PrsClosed          int64  `json:"prs_closed"`
	Deploys            int64  `json:"deploys"`
	LeadTimeSecondsP50 *int64 `json:"lead_time_seconds_p50"`
	LeadTimeSecondsP90 *int64 `json:"lead_time_seconds_p90"`
}

type DailyReviewLatency struct {
	Date                        string `json:"date"`
	RepoID                      int64  `json:"repo_id"`
	TimeToFirstReviewSecondsP50 *int64 `json:"time_to_first_review_seconds_p50"`
	TimeToFirstReviewSecondsP90 *int64 `json:"time_to_first_review_seconds_p90"`
	Count                       int64  `json:"count"`
}

type DailyReviewLoad struct {
	Date               string `json:"date"`
	RepoID             int64  `json:"repo_id"`
	ReviewerGhUserID   int64  `json:"reviewer_gh_user_id"`
	Reviews            int64  `json:"reviews"`
	ResponseMinutesP50 *int64 `json:"response_minutes_p50"`
}

type Deployment struct {
	GhID        int64     `json:"gh_id"`
	RepoID      int64     `json:"repo_id"`
	Environment string    `json:"environment"`
	Ref         string    `json:"ref"`
	Sha         string    `json:"sha"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type GhToken struct {
	ID           int64      `json:"id"`
	TenantID     int64      `json:"tenant_id"`
	Label        string     `json:"label"`
	EncryptedPat []byte     `json:"encrypted_pat"`
	Scopes       string     `json:"scopes"`
	ExpiresAt    *time.Time `json:"expires_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type GhUser struct {
	ID         int64      `json:"id"`
	TenantID   int64      `json:"tenant_id"`
	GhID       int64      `json:"gh_id"`
	Login      string     `json:"login"`
	Name       *string    `json:"name"`
	AvatarUrl  *string    `json:"avatar_url"`
	LastSeenAt *time.Time `json:"last_seen_at"`
}

type PrIssueComment struct {
	GhID           int64     `json:"gh_id"`
	PrRepoID       int64     `json:"pr_repo_id"`
	PrNumber       int64     `json:"pr_number"`
	AuthorGhUserID int64     `json:"author_gh_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type PrReview struct {
	GhID             int64     `json:"gh_id"`
	PrRepoID         int64     `json:"pr_repo_id"`
	PrNumber         int64     `json:"pr_number"`
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	State            string    `json:"state"`
	SubmittedAt      time.Time `json:"submitted_at"`
}

type PrReviewComment struct {
	GhID           int64     `json:"gh_id"`
	PrRepoID       int64     `json:"pr_repo_id"`
	PrNumber       int64     `json:"pr_number"`
	AuthorGhUserID int64     `json:"author_gh_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type PullRequest struct {
	RepoID         int64      `json:"repo_id"`
	Number         int64      `json:"number"`
	GhID           int64      `json:"gh_id"`
	AuthorGhUserID int64      `json:"author_gh_user_id"`
	State          string     `json:"state"`
	Title          string     `json:"title"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	MergedAt       *time.Time `json:"merged_at"`
	ClosedAt       *time.Time `json:"closed_at"`
	Additions      int64      `json:"additions"`
	Deletions      int64      `json:"deletions"`
	BaseRef        string     `json:"base_ref"`
	HeadRef        string     `json:"head_ref"`
	Draft          int64      `json:"draft"`
}

type Repo struct {
	ID            int64     `json:"id"`
	TenantID      int64     `json:"tenant_id"`
	ConnectionID  int64     `json:"connection_id"`
	GhID          int64     `json:"gh_id"`
	Owner         string    `json:"owner"`
	Name          string    `json:"name"`
	DefaultBranch string    `json:"default_branch"`
	Archived      int64     `json:"archived"`
	AddedAt       time.Time `json:"added_at"`
}

type RollupRun struct {
	Date       string     `json:"date"`
	Kind       string     `json:"kind"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	Ok         int64      `json:"ok"`
	Error      string     `json:"error"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SyncCursor struct {
	ConnectionID int64     `json:"connection_id"`
	Resource     string    `json:"resource"`
	Cursor       string    `json:"cursor"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type SyncRun struct {
	ID                 int64      `json:"id"`
	ConnectionID       int64      `json:"connection_id"`
	StartedAt          time.Time  `json:"started_at"`
	FinishedAt         *time.Time `json:"finished_at"`
	Ok                 int64      `json:"ok"`
	Items              int64      `json:"items"`
	RateLimitRemaining *int64     `json:"rate_limit_remaining"`
	Error              string     `json:"error"`
}

type Tenant struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	TenantID     int64     `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
