// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_issue_comments.sql

package sqlitedb

import (
	"context"
	"time"
)

const listIssueCommentsByPullRequest = `-- name: ListIssueCommentsByPullRequest :many
SELECT gh_id, pr_repo_id, pr_number, author_gh_user_id, created_at FROM pr_issue_comments
WHERE pr_repo_id = ?1 AND pr_number = ?2
ORDER BY created_at
`

type ListIssueCommentsByPullRequestParams struct {
	PrRepoID int64 `json:"pr_repo_id"`
	PrNumber int64 `json:"pr_number"`
}

func (q *Queries) ListIssueCommentsByPullRequest(ctx context.Context, arg ListIssueCommentsByPullRequestParams) ([]PrIssueComment, error) {
	rows, err := q.db.QueryContext(ctx, listIssueCommentsByPullRequest, arg.PrRepoID, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrIssueComment
	for rows.Next() {
		var i PrIssueComment
		if err := rows.Scan(
			&i.GhID,
			&i.PrRepoID,
			&i.PrNumber,
			&i.AuthorGhUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPullRequestIssueComment = `-- name: UpsertPullRequestIssueComment :exec
INSERT INTO pr_issue_comments (gh_id, pr_repo_id, pr_number, author_gh_user_id, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (gh_id) DO UPDATE SET
  pr_repo_id = excluded.pr_repo_id,
  pr_number = excluded.pr_number,
  author_gh_user_id = excluded.author_gh_user_id,
  created_at = excluded.created_at
`

type UpsertPullRequestIssueCommentParams struct {
	GhID           int64     `json:"gh_id"`
	PrRepoID       int64     `json:"pr_repo_id"`
	PrNumber       int64     `json:"pr_number"`
	AuthorGhUserID int64     `json:"author_gh_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) UpsertPullRequestIssueComment(ctx context.Context, arg UpsertPullRequestIssueCommentParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestIssueComment,
		arg.GhID,
		arg.PrRepoID,
		arg.PrNumber,
		arg.AuthorGhUserID,
		arg.CreatedAt,
	)
	return err
}
