// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_reviews.sql

package sqlitedb

import (
	"context"
	"time"
)

const listReviewsByPullRequest = `-- name: ListReviewsByPullRequest :many
SELECT gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at FROM pr_reviews
WHERE pr_repo_id = ?1 AND pr_number = ?2
ORDER BY submitted_at
`

type ListReviewsByPullRequestParams struct {
	PrRepoID int64 `json:"pr_repo_id"`
	PrNumber int64 `json:"pr_number"`
}

func (q *Queries) ListReviewsByPullRequest(ctx context.Context, arg ListReviewsByPullRequestParams) ([]PrReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByPullRequest, arg.PrRepoID, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrReview
	for rows.Next() {
		var i PrReview
		if err := rows.Scan(
			&i.GhID,
			&i.PrRepoID,
			&i.PrNumber,
			&i.ReviewerGhUserID,
			&i.State,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByReviewerBetween = `-- name: ListReviewsByReviewerBetween :many
SELECT gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at FROM pr_reviews
WHERE reviewer_gh_user_id = ?1
  AND submitted_at >= ?2
  AND submitted_at < ?3
ORDER BY submitted_at
`

type ListReviewsByReviewerBetweenParams struct {
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	FromTs           time.Time `json:"from_ts"`
	ToTs             time.Time `json:"to_ts"`
}

func (q *Queries) ListReviewsByReviewerBetween(ctx context.Context, arg ListReviewsByReviewerBetweenParams) ([]PrReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByReviewerBetween, arg.ReviewerGhUserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrReview
	for rows.Next() {
		var i PrReview
		if err := rows.Scan(
			&i.GhID,
			&i.PrRepoID,
			&i.PrNumber,
			&i.ReviewerGhUserID,
			&i.State,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsWithPRMetaForRepo = `-- name: ListReviewsWithPRMetaForRepo :many
SELECT pr.number AS pr_number,
       r.reviewer_gh_user_id AS reviewer_gh_user_id,
       r.submitted_at AS submitted_at,
       pr.created_at AS pr_created_at
FROM pr_reviews r
JOIN pull_requests pr
  ON pr.repo_id = r.pr_repo_id AND pr.number = r.pr_number
WHERE r.pr_repo_id = ?1
  AND r.reviewer_gh_user_id != 0
  AND r.reviewer_gh_user_id != pr.author_gh_user_id
`

type ListReviewsWithPRMetaForRepoRow struct {
	PrNumber         int64     `json:"pr_number"`
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	SubmittedAt      time.Time `json:"submitted_at"`
	PrCreatedAt      time.Time `json:"pr_created_at"`
}

// Every non-self non-ghost review in the repo, joined to its PR's
// number and created_at. No time filter; the aggregator does both
// the "first review per PR" reduction and the [from, to) bucketing
// in Go. Doing the MIN()/HAVING in SQL fights the modernc.org/sqlite
// driver: aggregate functions strip the column's TIMESTAMP type tag
// and the result comes back as a free-form string (YYYY-MM-DD
// HH:MM:SS +ZZZZ TZN), so Scan cannot unmarshal it into time.Time
// and unixepoch() refuses to parse it either.
func (q *Queries) ListReviewsWithPRMetaForRepo(ctx context.Context, repoID int64) ([]ListReviewsWithPRMetaForRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsWithPRMetaForRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsWithPRMetaForRepoRow
	for rows.Next() {
		var i ListReviewsWithPRMetaForRepoRow
		if err := rows.Scan(
			&i.PrNumber,
			&i.ReviewerGhUserID,
			&i.SubmittedAt,
			&i.PrCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPullRequestReview = `-- name: UpsertPullRequestReview :exec
INSERT INTO pr_reviews (gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (gh_id) DO UPDATE SET
  pr_repo_id = excluded.pr_repo_id,
  pr_number = excluded.pr_number,
  reviewer_gh_user_id = excluded.reviewer_gh_user_id,
  state = excluded.state,
  submitted_at = excluded.submitted_at
`

type UpsertPullRequestReviewParams struct {
	GhID             int64     `json:"gh_id"`
	PrRepoID         int64     `json:"pr_repo_id"`
	PrNumber         int64     `json:"pr_number"`
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	State            string    `json:"state"`
	SubmittedAt      time.Time `json:"submitted_at"`
}

func (q *Queries) UpsertPullRequestReview(ctx context.Context, arg UpsertPullRequestReviewParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestReview,
		arg.GhID,
		arg.PrRepoID,
		arg.PrNumber,
		arg.ReviewerGhUserID,
		arg.State,
		arg.SubmittedAt,
	)
	return err
}
