// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_reviews.sql

package sqlitedb

import (
	"context"
	"time"
)

const listReviewsByPullRequest = `-- name: ListReviewsByPullRequest :many
SELECT gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at FROM pr_reviews
WHERE pr_repo_id = ?1 AND pr_number = ?2
ORDER BY submitted_at
`

type ListReviewsByPullRequestParams struct {
	PrRepoID int64 `json:"pr_repo_id"`
	PrNumber int64 `json:"pr_number"`
}

func (q *Queries) ListReviewsByPullRequest(ctx context.Context, arg ListReviewsByPullRequestParams) ([]PrReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByPullRequest, arg.PrRepoID, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrReview
	for rows.Next() {
		var i PrReview
		if err := rows.Scan(
			&i.GhID,
			&i.PrRepoID,
			&i.PrNumber,
			&i.ReviewerGhUserID,
			&i.State,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByReviewerBetween = `-- name: ListReviewsByReviewerBetween :many
SELECT gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at FROM pr_reviews
WHERE reviewer_gh_user_id = ?1
  AND submitted_at >= ?2
  AND submitted_at < ?3
ORDER BY submitted_at
`

type ListReviewsByReviewerBetweenParams struct {
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	FromTs           time.Time `json:"from_ts"`
	ToTs             time.Time `json:"to_ts"`
}

func (q *Queries) ListReviewsByReviewerBetween(ctx context.Context, arg ListReviewsByReviewerBetweenParams) ([]PrReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByReviewerBetween, arg.ReviewerGhUserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrReview
	for rows.Next() {
		var i PrReview
		if err := rows.Scan(
			&i.GhID,
			&i.PrRepoID,
			&i.PrNumber,
			&i.ReviewerGhUserID,
			&i.State,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPullRequestReview = `-- name: UpsertPullRequestReview :exec
INSERT INTO pr_reviews (gh_id, pr_repo_id, pr_number, reviewer_gh_user_id, state, submitted_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (gh_id) DO UPDATE SET
  pr_repo_id = excluded.pr_repo_id,
  pr_number = excluded.pr_number,
  reviewer_gh_user_id = excluded.reviewer_gh_user_id,
  state = excluded.state,
  submitted_at = excluded.submitted_at
`

type UpsertPullRequestReviewParams struct {
	GhID             int64     `json:"gh_id"`
	PrRepoID         int64     `json:"pr_repo_id"`
	PrNumber         int64     `json:"pr_number"`
	ReviewerGhUserID int64     `json:"reviewer_gh_user_id"`
	State            string    `json:"state"`
	SubmittedAt      time.Time `json:"submitted_at"`
}

func (q *Queries) UpsertPullRequestReview(ctx context.Context, arg UpsertPullRequestReviewParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequestReview,
		arg.GhID,
		arg.PrRepoID,
		arg.PrNumber,
		arg.ReviewerGhUserID,
		arg.State,
		arg.SubmittedAt,
	)
	return err
}
