// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package sqlitedb

import (
	"context"
	"time"
)

const getPullRequest = `-- name: GetPullRequest :one
SELECT repo_id, number, gh_id, author_gh_user_id, state, title, created_at, updated_at, merged_at, closed_at, additions, deletions, base_ref, head_ref, draft FROM pull_requests WHERE repo_id = ?1 AND number = ?2
`

type GetPullRequestParams struct {
	RepoID int64 `json:"repo_id"`
	Number int64 `json:"number"`
}

func (q *Queries) GetPullRequest(ctx context.Context, arg GetPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequest, arg.RepoID, arg.Number)
	var i PullRequest
	err := row.Scan(
		&i.RepoID,
		&i.Number,
		&i.GhID,
		&i.AuthorGhUserID,
		&i.State,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.Additions,
		&i.Deletions,
		&i.BaseRef,
		&i.HeadRef,
		&i.Draft,
	)
	return i, err
}

const listMergedPullRequestsByRepoBetween = `-- name: ListMergedPullRequestsByRepoBetween :many
SELECT repo_id, number, gh_id, author_gh_user_id, state, title, created_at, updated_at, merged_at, closed_at, additions, deletions, base_ref, head_ref, draft FROM pull_requests
WHERE repo_id = ?1
  AND merged_at IS NOT NULL
  AND merged_at >= ?2
  AND merged_at < ?3
ORDER BY merged_at
`

type ListMergedPullRequestsByRepoBetweenParams struct {
	RepoID int64      `json:"repo_id"`
	FromTs *time.Time `json:"from_ts"`
	ToTs   *time.Time `json:"to_ts"`
}

func (q *Queries) ListMergedPullRequestsByRepoBetween(ctx context.Context, arg ListMergedPullRequestsByRepoBetweenParams) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listMergedPullRequestsByRepoBetween, arg.RepoID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.RepoID,
			&i.Number,
			&i.GhID,
			&i.AuthorGhUserID,
			&i.State,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MergedAt,
			&i.ClosedAt,
			&i.Additions,
			&i.Deletions,
			&i.BaseRef,
			&i.HeadRef,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestsByRepoBetween = `-- name: ListPullRequestsByRepoBetween :many
SELECT repo_id, number, gh_id, author_gh_user_id, state, title, created_at, updated_at, merged_at, closed_at, additions, deletions, base_ref, head_ref, draft FROM pull_requests
WHERE repo_id = ?1
  AND created_at >= ?2
  AND created_at < ?3
ORDER BY created_at
`

type ListPullRequestsByRepoBetweenParams struct {
	RepoID int64     `json:"repo_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

func (q *Queries) ListPullRequestsByRepoBetween(ctx context.Context, arg ListPullRequestsByRepoBetweenParams) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequestsByRepoBetween, arg.RepoID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.RepoID,
			&i.Number,
			&i.GhID,
			&i.AuthorGhUserID,
			&i.State,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MergedAt,
			&i.ClosedAt,
			&i.Additions,
			&i.Deletions,
			&i.BaseRef,
			&i.HeadRef,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestsByRepoUpdatedSince = `-- name: ListPullRequestsByRepoUpdatedSince :many
SELECT repo_id, number, gh_id, author_gh_user_id, state, title, created_at, updated_at, merged_at, closed_at, additions, deletions, base_ref, head_ref, draft FROM pull_requests
WHERE repo_id = ?1
  AND updated_at > ?2
ORDER BY updated_at
`

type ListPullRequestsByRepoUpdatedSinceParams struct {
	RepoID int64     `json:"repo_id"`
	Since  time.Time `json:"since"`
}

func (q *Queries) ListPullRequestsByRepoUpdatedSince(ctx context.Context, arg ListPullRequestsByRepoUpdatedSinceParams) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequestsByRepoUpdatedSince, arg.RepoID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.RepoID,
			&i.Number,
			&i.GhID,
			&i.AuthorGhUserID,
			&i.State,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MergedAt,
			&i.ClosedAt,
			&i.Additions,
			&i.Deletions,
			&i.BaseRef,
			&i.HeadRef,
			&i.Draft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPullRequest = `-- name: UpsertPullRequest :exec
INSERT INTO pull_requests (
  repo_id, number, gh_id, author_gh_user_id, state, title,
  created_at, updated_at, merged_at, closed_at, additions, deletions,
  base_ref, head_ref, draft
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10, ?11, ?12,
  ?13, ?14, ?15
)
ON CONFLICT (repo_id, number) DO UPDATE SET
  gh_id = excluded.gh_id,
  author_gh_user_id = excluded.author_gh_user_id,
  state = excluded.state,
  title = excluded.title,
  updated_at = excluded.updated_at,
  merged_at = excluded.merged_at,
  closed_at = excluded.closed_at,
  additions = excluded.additions,
  deletions = excluded.deletions,
  base_ref = excluded.base_ref,
  head_ref = excluded.head_ref,
  draft = excluded.draft
`

type UpsertPullRequestParams struct {
	RepoID         int64      `json:"repo_id"`
	Number         int64      `json:"number"`
	GhID           int64      `json:"gh_id"`
	AuthorGhUserID int64      `json:"author_gh_user_id"`
	State          string     `json:"state"`
	Title          string     `json:"title"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	MergedAt       *time.Time `json:"merged_at"`
	ClosedAt       *time.Time `json:"closed_at"`
	Additions      int64      `json:"additions"`
	Deletions      int64      `json:"deletions"`
	BaseRef        string     `json:"base_ref"`
	HeadRef        string     `json:"head_ref"`
	Draft          int64      `json:"draft"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequest,
		arg.RepoID,
		arg.Number,
		arg.GhID,
		arg.AuthorGhUserID,
		arg.State,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.Additions,
		arg.Deletions,
		arg.BaseRef,
		arg.HeadRef,
		arg.Draft,
	)
	return err
}
