// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
	"time"
)

type Querier interface {
	CountConnectionsByToken(ctx context.Context, tokenID int64) (int64, error)
	CountFailedSyncRunsSince(ctx context.Context, since time.Time) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID int64) (int64, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateGhToken(ctx context.Context, arg CreateGhTokenParams) (GhToken, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConnection(ctx context.Context, id int64) error
	DeleteDailyEngineerStatsByDateRepo(ctx context.Context, arg DeleteDailyEngineerStatsByDateRepoParams) error
	DeleteDailyRepoStatsByDateRepo(ctx context.Context, arg DeleteDailyRepoStatsByDateRepoParams) error
	DeleteExpiredSessions(ctx context.Context, now time.Time) error
	DeleteGhToken(ctx context.Context, id int64) error
	DeleteRepo(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	FinishRollupRun(ctx context.Context, arg FinishRollupRunParams) error
	FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error
	GetCommit(ctx context.Context, arg GetCommitParams) (Commit, error)
	GetConnection(ctx context.Context, id int64) (Connection, error)
	GetGhToken(ctx context.Context, id int64) (GhToken, error)
	GetGhUser(ctx context.Context, id int64) (GhUser, error)
	GetGhUserByGhID(ctx context.Context, arg GetGhUserByGhIDParams) (GhUser, error)
	GetLastFailedSyncRun(ctx context.Context, connectionID int64) (SyncRun, error)
	GetLastSuccessfulSyncRun(ctx context.Context, connectionID int64) (SyncRun, error)
	GetLatestSyncRun(ctx context.Context, connectionID int64) (SyncRun, error)
	GetPullRequest(ctx context.Context, arg GetPullRequestParams) (PullRequest, error)
	GetRepo(ctx context.Context, id int64) (Repo, error)
	GetRepoByGhID(ctx context.Context, arg GetRepoByGhIDParams) (Repo, error)
	GetRollupRun(ctx context.Context, arg GetRollupRunParams) (RollupRun, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (SyncCursor, error)
	GetSyncRun(ctx context.Context, id int64) (SyncRun, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	ListActiveConnections(ctx context.Context) ([]Connection, error)
	ListAllRepos(ctx context.Context) ([]Repo, error)
	ListCommitsByAuthorBetween(ctx context.Context, arg ListCommitsByAuthorBetweenParams) ([]Commit, error)
	ListCommitsByRepoBetween(ctx context.Context, arg ListCommitsByRepoBetweenParams) ([]Commit, error)
	ListConnectionsByTenant(ctx context.Context, tenantID int64) ([]Connection, error)
	ListDailyEngineerStatsByRepoBetween(ctx context.Context, arg ListDailyEngineerStatsByRepoBetweenParams) ([]DailyEngineerStat, error)
	ListDailyEngineerStatsByUserBetween(ctx context.Context, arg ListDailyEngineerStatsByUserBetweenParams) ([]DailyEngineerStat, error)
	ListDailyRepoStatsByRepoBetween(ctx context.Context, arg ListDailyRepoStatsByRepoBetweenParams) ([]DailyRepoStat, error)
	ListDailyReviewLatencyByRepoBetween(ctx context.Context, arg ListDailyReviewLatencyByRepoBetweenParams) ([]DailyReviewLatency, error)
	ListDailyReviewLoadByRepoBetween(ctx context.Context, arg ListDailyReviewLoadByRepoBetweenParams) ([]DailyReviewLoad, error)
	ListDailyReviewLoadByReviewerBetween(ctx context.Context, arg ListDailyReviewLoadByReviewerBetweenParams) ([]DailyReviewLoad, error)
	ListDeploymentsByRepoBetween(ctx context.Context, arg ListDeploymentsByRepoBetweenParams) ([]Deployment, error)
	ListGhTokensByTenant(ctx context.Context, tenantID int64) ([]GhToken, error)
	ListGhUsersByTenant(ctx context.Context, tenantID int64) ([]GhUser, error)
	ListIssueCommentsByPullRequest(ctx context.Context, arg ListIssueCommentsByPullRequestParams) ([]PrIssueComment, error)
	ListMergedPullRequestsByRepoBetween(ctx context.Context, arg ListMergedPullRequestsByRepoBetweenParams) ([]PullRequest, error)
	ListPullRequestsByRepoBetween(ctx context.Context, arg ListPullRequestsByRepoBetweenParams) ([]PullRequest, error)
	ListPullRequestsByRepoUpdatedSince(ctx context.Context, arg ListPullRequestsByRepoUpdatedSinceParams) ([]PullRequest, error)
	ListReposByConnection(ctx context.Context, connectionID int64) ([]Repo, error)
	ListReposByTenant(ctx context.Context, tenantID int64) ([]Repo, error)
	ListReviewCommentsByPullRequest(ctx context.Context, arg ListReviewCommentsByPullRequestParams) ([]PrReviewComment, error)
	ListReviewsByPullRequest(ctx context.Context, arg ListReviewsByPullRequestParams) ([]PrReview, error)
	ListReviewsByReviewerBetween(ctx context.Context, arg ListReviewsByReviewerBetweenParams) ([]PrReview, error)
	ListSuccessfulRollupDates(ctx context.Context, arg ListSuccessfulRollupDatesParams) ([]string, error)
	ListSyncCursorsByConnection(ctx context.Context, connectionID int64) ([]SyncCursor, error)
	ListSyncRunsByConnection(ctx context.Context, arg ListSyncRunsByConnectionParams) ([]SyncRun, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsersByTenant(ctx context.Context, tenantID int64) ([]User, error)
	PruneSyncRunsByConnection(ctx context.Context, arg PruneSyncRunsByConnectionParams) error
	StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error)
	UpdateConnectionLastSync(ctx context.Context, arg UpdateConnectionLastSyncParams) error
	UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error
	UpdateRepoArchived(ctx context.Context, arg UpdateRepoArchivedParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertCommit(ctx context.Context, arg UpsertCommitParams) error
	UpsertDailyEngineerStats(ctx context.Context, arg UpsertDailyEngineerStatsParams) error
	UpsertDailyRepoStats(ctx context.Context, arg UpsertDailyRepoStatsParams) error
	UpsertDailyReviewLatency(ctx context.Context, arg UpsertDailyReviewLatencyParams) error
	UpsertDailyReviewLoad(ctx context.Context, arg UpsertDailyReviewLoadParams) error
	UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) error
	UpsertGhUser(ctx context.Context, arg UpsertGhUserParams) (GhUser, error)
	UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error
	UpsertPullRequestIssueComment(ctx context.Context, arg UpsertPullRequestIssueCommentParams) error
	UpsertPullRequestReview(ctx context.Context, arg UpsertPullRequestReviewParams) error
	UpsertPullRequestReviewComment(ctx context.Context, arg UpsertPullRequestReviewCommentParams) error
	UpsertRollupRunStart(ctx context.Context, arg UpsertRollupRunStartParams) (RollupRun, error)
	UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error
}

var _ Querier = (*Queries)(nil)
