// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package sqlitedb

import (
	"context"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (tenant_id, connection_id, gh_id, owner, name, default_branch, archived)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at
`

type CreateRepoParams struct {
	TenantID      int64  `json:"tenant_id"`
	ConnectionID  int64  `json:"connection_id"`
	GhID          int64  `json:"gh_id"`
	Owner         string `json:"owner"`
	Name          string `json:"name"`
	DefaultBranch string `json:"default_branch"`
	Archived      int64  `json:"archived"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, createRepo,
		arg.TenantID,
		arg.ConnectionID,
		arg.GhID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.Archived,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConnectionID,
		&i.GhID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Archived,
		&i.AddedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = ?1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at FROM repos WHERE id = ?1
`

func (q *Queries) GetRepo(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConnectionID,
		&i.GhID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Archived,
		&i.AddedAt,
	)
	return i, err
}

const getRepoByGhID = `-- name: GetRepoByGhID :one
SELECT id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at FROM repos WHERE tenant_id = ?1 AND gh_id = ?2
`

type GetRepoByGhIDParams struct {
	TenantID int64 `json:"tenant_id"`
	GhID     int64 `json:"gh_id"`
}

func (q *Queries) GetRepoByGhID(ctx context.Context, arg GetRepoByGhIDParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByGhID, arg.TenantID, arg.GhID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConnectionID,
		&i.GhID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Archived,
		&i.AddedAt,
	)
	return i, err
}

const listAllRepos = `-- name: ListAllRepos :many
SELECT id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at FROM repos ORDER BY id
`

func (q *Queries) ListAllRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.GhID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Archived,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByConnection = `-- name: ListReposByConnection :many
SELECT id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at FROM repos WHERE connection_id = ?1 ORDER BY owner, name
`

func (q *Queries) ListReposByConnection(ctx context.Context, connectionID int64) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.GhID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Archived,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByTenant = `-- name: ListReposByTenant :many
SELECT id, tenant_id, connection_id, gh_id, owner, name, default_branch, archived, added_at FROM repos WHERE tenant_id = ?1 ORDER BY owner, name
`

func (q *Queries) ListReposByTenant(ctx context.Context, tenantID int64) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConnectionID,
			&i.GhID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Archived,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoArchived = `-- name: UpdateRepoArchived :exec
UPDATE repos SET archived = ?1 WHERE id = ?2
`

type UpdateRepoArchivedParams struct {
	Archived int64 `json:"archived"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateRepoArchived(ctx context.Context, arg UpdateRepoArchivedParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoArchived, arg.Archived, arg.ID)
	return err
}
