// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollup_runs.sql

package sqlitedb

import (
	"context"
	"time"
)

const finishRollupRun = `-- name: FinishRollupRun :exec
UPDATE rollup_runs
SET finished_at = ?1,
    ok = ?2,
    error = ?3
WHERE date = ?4 AND kind = ?5
`

type FinishRollupRunParams struct {
	FinishedAt *time.Time `json:"finished_at"`
	Ok         int64      `json:"ok"`
	Error      string     `json:"error"`
	Date       string     `json:"date"`
	Kind       string     `json:"kind"`
}

func (q *Queries) FinishRollupRun(ctx context.Context, arg FinishRollupRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRollupRun,
		arg.FinishedAt,
		arg.Ok,
		arg.Error,
		arg.Date,
		arg.Kind,
	)
	return err
}

const getRollupRun = `-- name: GetRollupRun :one
SELECT date, kind, started_at, finished_at, ok, error FROM rollup_runs WHERE date = ?1 AND kind = ?2
`

type GetRollupRunParams struct {
	Date string `json:"date"`
	Kind string `json:"kind"`
}

func (q *Queries) GetRollupRun(ctx context.Context, arg GetRollupRunParams) (RollupRun, error) {
	row := q.db.QueryRowContext(ctx, getRollupRun, arg.Date, arg.Kind)
	var i RollupRun
	err := row.Scan(
		&i.Date,
		&i.Kind,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Error,
	)
	return i, err
}

const listSuccessfulRollupDates = `-- name: ListSuccessfulRollupDates :many
SELECT date FROM rollup_runs
WHERE kind = ?1 AND ok = 1 AND date >= ?2
ORDER BY date DESC
`

type ListSuccessfulRollupDatesParams struct {
	Kind  string `json:"kind"`
	Since string `json:"since"`
}

func (q *Queries) ListSuccessfulRollupDates(ctx context.Context, arg ListSuccessfulRollupDatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSuccessfulRollupDates, arg.Kind, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var date string
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRollupRunStart = `-- name: UpsertRollupRunStart :one
INSERT INTO rollup_runs (date, kind, started_at, finished_at, ok, error)
VALUES (?1, ?2, ?3, NULL, 0, '')
ON CONFLICT(date, kind) DO UPDATE SET
  started_at = excluded.started_at,
  finished_at = NULL,
  ok = 0,
  error = ''
RETURNING date, kind, started_at, finished_at, ok, error
`

type UpsertRollupRunStartParams struct {
	Date      string    `json:"date"`
	Kind      string    `json:"kind"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) UpsertRollupRunStart(ctx context.Context, arg UpsertRollupRunStartParams) (RollupRun, error) {
	row := q.db.QueryRowContext(ctx, upsertRollupRunStart, arg.Date, arg.Kind, arg.StartedAt)
	var i RollupRun
	err := row.Scan(
		&i.Date,
		&i.Kind,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Error,
	)
	return i, err
}
