// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_cursors.sql

package sqlitedb

import (
	"context"
	"time"
)

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT connection_id, resource, cursor, updated_at FROM sync_cursors
WHERE connection_id = ?1 AND resource = ?2
`

type GetSyncCursorParams struct {
	ConnectionID int64  `json:"connection_id"`
	Resource     string `json:"resource"`
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (SyncCursor, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.ConnectionID, arg.Resource)
	var i SyncCursor
	err := row.Scan(
		&i.ConnectionID,
		&i.Resource,
		&i.Cursor,
		&i.UpdatedAt,
	)
	return i, err
}

const listSyncCursorsByConnection = `-- name: ListSyncCursorsByConnection :many
SELECT connection_id, resource, cursor, updated_at FROM sync_cursors
WHERE connection_id = ?1
ORDER BY resource
`

func (q *Queries) ListSyncCursorsByConnection(ctx context.Context, connectionID int64) ([]SyncCursor, error) {
	rows, err := q.db.QueryContext(ctx, listSyncCursorsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncCursor
	for rows.Next() {
		var i SyncCursor
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Resource,
			&i.Cursor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (connection_id, resource, cursor, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (connection_id, resource) DO UPDATE SET
  cursor = excluded.cursor,
  updated_at = excluded.updated_at
`

type UpsertSyncCursorParams struct {
	ConnectionID int64     `json:"connection_id"`
	Resource     string    `json:"resource"`
	Cursor       string    `json:"cursor"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor,
		arg.ConnectionID,
		arg.Resource,
		arg.Cursor,
		arg.UpdatedAt,
	)
	return err
}
