// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_runs.sql

package sqlitedb

import (
	"context"
	"time"
)

const countFailedSyncRunsSince = `-- name: CountFailedSyncRunsSince :one
SELECT COUNT(*) FROM sync_runs
WHERE finished_at IS NOT NULL
  AND ok = 0
  AND started_at >= ?1
`

func (q *Queries) CountFailedSyncRunsSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedSyncRunsSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at = ?1,
    ok = ?2,
    items = ?3,
    rate_limit_remaining = ?4,
    error = ?5
WHERE id = ?6
`

type FinishSyncRunParams struct {
	FinishedAt         *time.Time `json:"finished_at"`
	Ok                 int64      `json:"ok"`
	Items              int64      `json:"items"`
	RateLimitRemaining *int64     `json:"rate_limit_remaining"`
	Error              string     `json:"error"`
	ID                 int64      `json:"id"`
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, finishSyncRun,
		arg.FinishedAt,
		arg.Ok,
		arg.Items,
		arg.RateLimitRemaining,
		arg.Error,
		arg.ID,
	)
	return err
}

const getLastFailedSyncRun = `-- name: GetLastFailedSyncRun :one
SELECT id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error FROM sync_runs
WHERE connection_id = ?1
  AND ok = 0
  AND error != ''
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastFailedSyncRun(ctx context.Context, connectionID int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, getLastFailedSyncRun, connectionID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Items,
		&i.RateLimitRemaining,
		&i.Error,
	)
	return i, err
}

const getLastSuccessfulSyncRun = `-- name: GetLastSuccessfulSyncRun :one
SELECT id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error FROM sync_runs
WHERE connection_id = ?1
  AND ok = 1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulSyncRun(ctx context.Context, connectionID int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, getLastSuccessfulSyncRun, connectionID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Items,
		&i.RateLimitRemaining,
		&i.Error,
	)
	return i, err
}

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error FROM sync_runs
WHERE connection_id = ?1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncRun(ctx context.Context, connectionID int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestSyncRun, connectionID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Items,
		&i.RateLimitRemaining,
		&i.Error,
	)
	return i, err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error FROM sync_runs WHERE id = ?1
`

func (q *Queries) GetSyncRun(ctx context.Context, id int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Items,
		&i.RateLimitRemaining,
		&i.Error,
	)
	return i, err
}

const listSyncRunsByConnection = `-- name: ListSyncRunsByConnection :many
SELECT id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error FROM sync_runs
WHERE connection_id = ?1
ORDER BY started_at DESC
LIMIT ?2
`

type ListSyncRunsByConnectionParams struct {
	ConnectionID int64 `json:"connection_id"`
	LimitN       int64 `json:"limit_n"`
}

func (q *Queries) ListSyncRunsByConnection(ctx context.Context, arg ListSyncRunsByConnectionParams) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRunsByConnection, arg.ConnectionID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncRun
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Ok,
			&i.Items,
			&i.RateLimitRemaining,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSyncRunsByConnection = `-- name: PruneSyncRunsByConnection :exec
DELETE FROM sync_runs AS old
WHERE old.connection_id = ?1
  AND old.id NOT IN (
    SELECT keep.id FROM sync_runs AS keep
    WHERE keep.connection_id = ?1
    ORDER BY keep.started_at DESC
    LIMIT ?2
  )
`

type PruneSyncRunsByConnectionParams struct {
	ConnectionID int64 `json:"connection_id"`
	KeepN        int64 `json:"keep_n"`
}

func (q *Queries) PruneSyncRunsByConnection(ctx context.Context, arg PruneSyncRunsByConnectionParams) error {
	_, err := q.db.ExecContext(ctx, pruneSyncRunsByConnection, arg.ConnectionID, arg.KeepN)
	return err
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (connection_id, started_at)
VALUES (?1, ?2)
RETURNING id, connection_id, started_at, finished_at, ok, items, rate_limit_remaining, error
`

type StartSyncRunParams struct {
	ConnectionID int64     `json:"connection_id"`
	StartedAt    time.Time `json:"started_at"`
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, startSyncRun, arg.ConnectionID, arg.StartedAt)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Items,
		&i.RateLimitRemaining,
		&i.Error,
	)
	return i, err
}
