// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlitedb

import (
	"context"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES (?1)
RETURNING id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at FROM tenants WHERE id = ?1
`

func (q *Queries) GetTenant(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, created_at FROM tenants ORDER BY id
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
