#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../../.."

fail() { echo "VERIFY FAIL: $1" >&2; exit 1; }

# Required deps in package.json
node -e "
  const p = require('./web/package.json');
  const need = {
    deps: ['@tanstack/react-router', '@tanstack/react-query'],
    devDeps: ['@tanstack/router-plugin'],
  };
  for (const d of need.deps) if (!p.dependencies?.[d]) { console.error('missing dep: '+d); process.exit(1); }
  for (const d of need.devDeps) if (!p.devDependencies?.[d]) { console.error('missing devDep: '+d); process.exit(1); }
" || fail "package.json missing tanstack deps"

# vite config wires the router plugin
grep -q "tanstackRouter" web/vite.config.ts || fail "vite.config.ts missing tanstackRouter plugin"

# Routes exist
[ -f web/src/routes/__root.tsx ] || fail "web/src/routes/__root.tsx missing"
[ -f web/src/routes/index.tsx ] || fail "web/src/routes/index.tsx missing"

# main.tsx wires RouterProvider + QueryClientProvider
grep -q "RouterProvider" web/src/main.tsx || fail "main.tsx missing RouterProvider"
grep -q "QueryClientProvider" web/src/main.tsx || fail "main.tsx missing QueryClientProvider"

# Button component installed by shadcn
[ -f web/src/components/ui/button.tsx ] || fail "shadcn Button not installed at web/src/components/ui/button.tsx"

# Build works
pnpm -C web install --frozen-lockfile >/dev/null
pnpm -C web build >/dev/null
[ -f web/dist/index.html ] || fail "build output missing"

# Generated route tree exists after build
[ -f web/src/routeTree.gen.ts ] || fail "routeTree.gen.ts not generated by the plugin"

echo "verify ok"
